<?php

return [

    'name' => 'Name',
    'description' => 'Description',
    'active' => 'Active',


    'nameExamples' => 'TPS Report, Daily Activity Report, Inquiry Summary, etc...',
    'descriptionDescription' => 'Describe the purpose of this report. This information will appear at the top of the report each time it is generated. Include details on how to use the information in the report to help guide business decisions and activities.',
    'descriptionExample' => 'Describe this report...',
    'activeDescription' => 'Reports marked inactive cannot be generated by any staff member.',

    'teamAccessApproval' => 'Team Access Approval',
    'teamAccessApprovalDescription' => 'This Report will only be accessible by members of these teams.',
    'teamAccessApprovalShortDescription' => 'This Report is only accessible by members of these teams:',
    'unrestrictedDescription' => 'This Report is accessible by all of your staff.',

];
